{"uuid": "c3d06945-a3a7-4f64-9835-9cd50b175ae9", "children": ["4791268d-fd6f-4b02-a270-6940730ab8cf"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/chromedriver unexpectedly exited. Status code was: -9\n\n", "trace": "  File \"/Users/apple/PycharmProjects/noocommerceapp/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/apple/PycharmProjects/noocommerceapp/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/apple/PycharmProjects/noocommerceapp/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/apple/PycharmProjects/noocommerceapp/testCases/conftest.py\", line 9, in setup\n    driver = webdriver.Chrome()\n  File \"/Users/apple/PycharmProjects/noocommerceapp/venv/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 49, in __init__\n    super().__init__(\n  File \"/Users/apple/PycharmProjects/noocommerceapp/venv/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py\", line 51, in __init__\n    self.service.start()\n  File \"/Users/apple/PycharmProjects/noocommerceapp/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py\", line 97, in start\n    self.assert_process_still_running()\n  File \"/Users/apple/PycharmProjects/noocommerceapp/venv/lib/python3.8/site-packages/selenium/webdriver/common/service.py\", line 110, in assert_process_still_running\n    raise WebDriverException(f\"Service {self._path} unexpectedly exited. Status code was: {return_code}\")\n"}, "start": 1692365884456, "stop": 1692365901101}], "start": 1692365884456, "stop": 1692365901201}